package com.nocountry.rentify.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;


@Schema(description = "Response object for a successful login operation, including user ID, username, role, and authentication token.")
public record LoginRes(

        @Schema(description = "The unique identifier of the user, typically auto-generated by the system.", example = "123")
        Long id,

        @Schema(description = "The username associated with the user. This field is typically used for users with the 'REALTOR' role.", example = "realtor_johndoe")
        String username,

        @Schema(description = "The first name of the user.", example = "John")
        String name,

        @Schema(description = "The last name of the user.", example = "Doe")
        String lastname,

        @Schema(description = "A URL pointing to the user's profile photo or avatar.", example = "https://example.com/images/user123.jpg")
        String photo,

        @Schema(description = "The role assigned to the user, determining their permissions in the system. Common roles include 'USER', 'ADMIN', etc.", example = "USER")
        String role,

        @Schema(description = "The JWT authentication token issued to the user after a successful login. This token is used to authenticate the user's requests to protected endpoints.", example = "eyJhbGciOiJIUzI1.eyJzdWIiOiIxMjM_adQssw5c")
        String token
) {
}
